version: "3.0"

services:
  myiis:
    build:
      context: .
      dockerfile: Dockerfile
    image: myiis
    container_name: chatwebapplication
    platform: windows
    isolation: hyperv
    environment:
      - TZ=Asia/Taipei
    ports:
      - "80:80"
      - "1443:1443"


